### ISSUE TITLE
[1.19.2 / Forge] Suggestion to update Forge version to match Fabric one.

### ISSUE THREAD

**Issue by murao-kun** [valoeghese/Dash#3]
Hello! I was searching for a dash mod for my modpack and your one is seems to be perfect one that I would like to prefer.
Do you have to keep the forge version up to date with fabric one.

By the way big thank you for your amazing job, the mod is simple but very clean and good quality!

**Comment by valoeghese** [comment]
I'll close this for now because the 1.18 forge version is up-to-date. I'll release forge versions for newer versions of minecraft at some time in the future
