### ISSUE TITLE
Unable to sprint even after disabling double-tap dashing

### ISSUE THREAD

**Issue by PatchTheCat** [valoeghese/Dash#4]
When you change your Dash key bind you aren't able to sprint by double tapping the forward key. Sprinting with the left control key still works.

**Comment by valoeghese** [comment]
Assigning the dash keybind doesn't disable double-tap dashing, but if double-tap dashing is disabled in the config it should restore double tap sprinting. I've tested in-game and can confirm this doesn't work. I'm looking into this.

**Comment by valoeghese** [comment]
Fixed for fabric 1.18, not yet for other versions
